### ISSUE TITLE
[疑似bug]:隐藏战绩相关问题

### ISSUE THREAD

**Issue by sitherx** [SangonomiyaKoko/Kokomi_Bot#2]
某群友查询wws me recent 7，bot回复该玩家隐藏战绩。我确认了他的战绩是公开状态（非隐藏或仅通过链接提供，但先前隐藏过一段时间），且可使用kokomi查询他的wws me，group rank功能也有他的数据；查询wws me recent 2-7日均回复该玩家隐藏战绩，查询wws me recent 1则回复该日期范围内没有随机战斗的数据。
他应该是在隐藏战绩时绑定了账号，可能原因是kkm不会每日尝试更新绑定时隐藏战绩账号的数据。
请问一下kkm服务器端对隐藏战绩的账号数据是如何处理的，以及是否可能解决无法查询wws me recent 的问题。

go-cqhttp、nonebot端均没有值得注意的日志。
如需要可提供玩家id。

**Comment by SangonomiyaKoko** [comment]
## kokomi计算recent的逻辑是这样的：
1. 首先数据库每天会对所有用户进行4次数据更新，保存用户当前时间的数据，如果该用户隐藏战绩当然是无法记录数据
2. 要获取 recent 7的数据就是**拿今天的数据和7天前的数据做比较**，差值就是这7天时间里面这个用户所战斗的记录

那么就非常好理解这个问题，你群友7天前的数据是隐藏战绩的，那么recent7获取数据时就拿不到7天前这个账号的数据，也就无法计算7天内的战斗场数。

~~还有一点，你刚好在我玩wws2km骑脸的时候发issue，然后右下角弹出个邮件......  **你！赔！我！场！均！**（大哭大闹）~~

**Comment by sitherx** [comment]
我有罪 我改悔力）
（不会又骑脸时发罢
