### ISSUE TITLE
[feature request]使用webp编码水表图片

### ISSUE THREAD

**Issue by nidbCN** [SangonomiyaKoko/Kokomi_Bot#4]
# 现状

目前bot使用png发送图片，每张水表在 `400kb` 左右，部分 recent 水表可能有 `4mb`。

# 切换 webp 的优势

可以考虑切换至webp编码，有以下好处：

1. 减轻服务器带宽压力，以某位大窝批群友的 `recent 180` 为例，使用 `webp` 编码可将体积缩小为原来的 20% 并且仍保持文字清晰可见（这还是几个较现代编码技术中最拉跨的webp，没有加任何参数的结果），可以有效节省带宽；
2.  加快 bot 响应速度，QQ 发图片有一定的时间消耗在图片上传上（如果服务器带宽小的话还是有相当长的时间）；
3.  减少用户 QQ 缓存占用的存储空间

# 为什么是 wbep 而不是其它？

目前 QQ 仅支持上传发送 `webp` 与 `avif` 格式的图片，未对 `JPEG-XL` 与 `heic/heif` 提供支持，经过测试使用 avif 格式的图片无法正常发送，且 `avif` 编码较为消耗时间。

# 可行性分析

可以使用[ImageMagick](https://wiki.python.org/moin/ImageMagick)、[libvips](https://github.com/libvips/pyvips)等经典、高效的库进行处理，他们用起来应该不难，资料也够

然后参数的话就需要慢慢试试了，但是感觉可以。如果说HTML渲染库不支持渲染到webp，转到位图再递交给上面所说的也没问题。

~~当然手搓libwebp也可以~~

**Comment by SangonomiyaKoko** [comment]
已经计划在下一个大版本更新种采用，thx

**Comment by nidbCN** [comment]
> 已经计划在下一个大版本更新种采用，thx

好耶！
